# Generated by Django 5.2.9 on 2026-02-16 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientvital',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='followupmedicine',
            index=models.Index(fields=['followup'], name='patients_fo_followu_323b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='followupmedicine',
            index=models.Index(fields=['created_at'], name='patients_fo_created_f6930c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalfollowup',
            index=models.Index(fields=['medical_history'], name='patients_me_medical_3e6962_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalfollowup',
            index=models.Index(fields=['created_at'], name='patients_me_created_8a134f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['patient'], name='patients_me_patient_9d2064_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['created_at'], name='patients_me_created_7b3b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvital',
            index=models.Index(fields=['patient'], name='patients_pa_patient_fa2d70_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvital',
            index=models.Index(fields=['created_at'], name='patients_pa_created_1e339c_idx'),
        ),
    ]
