# Generated by Django 5.2.9 on 2026-01-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalfollowup',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfollowup',
            name='clinical_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfollowup',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfollowup',
            name='patient_complaints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='diagnosis_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='blood_pressure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='heart_rate_bpm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='height_cm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='temperature_celsius',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='weight_kg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='followupmedicine',
            index=models.Index(fields=['followup'], name='patients_fo_followu_323b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='followupmedicine',
            index=models.Index(fields=['created_at'], name='patients_fo_created_f6930c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalfollowup',
            index=models.Index(fields=['medical_history'], name='patients_me_medical_3e6962_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalfollowup',
            index=models.Index(fields=['created_at'], name='patients_me_created_8a134f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['patient'], name='patients_me_patient_9d2064_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['created_at'], name='patients_me_created_7b3b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvital',
            index=models.Index(fields=['patient'], name='patients_pa_patient_fa2d70_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvital',
            index=models.Index(fields=['created_at'], name='patients_pa_created_1e339c_idx'),
        ),
    ]
