# Generated by Django 5.2.7 on 2025-11-08 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctors_user'),
        ('users', '0002_customuser_linked_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='linked_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctors'),
        ),
    ]
