# Generated by Django 5.2.7 on 2025-11-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_otp_code_remove_otp_created_at_otp_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='otp_expires_at',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
