# Generated by Django 5.2.7 on 2025-11-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_otp_otp_expires_at_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
