# Generated by Django 5.2.7 on 2025-11-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_expires_at_customuser_otp_delete_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='expires_at',
            new_name='otp_expires_at',
        ),
    ]
