# Generated by Django 5.2.9 on 2026-02-16 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='head_of_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headed_families', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.family'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='patients.patient'),
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.UniqueConstraint(fields=('head_of_family', 'name'), name='unique_family_per_head'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('family', 'patient'), name='unique_patient_per_family'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('patient',), name='unique_patient_global_family'),
        ),
    ]
