# Generated by Django 5.2.9 on 2026-02-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.TextField()),
                ('policy_number', models.TextField()),
                ('coverage_type', models.TextField()),
                ('coverage_amount', models.TextField()),
                ('validity_start', models.DateField()),
                ('validity_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='patients.patient')),
            ],
            options={
                'ordering': ['-validity_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='insurance_docs/')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='insurance.insurance')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='insurance',
            index=models.Index(fields=['patient'], name='insurance_i_patient_e6ae3d_idx'),
        ),
        migrations.AddIndex(
            model_name='insurance',
            index=models.Index(fields=['validity_end'], name='insurance_i_validit_ebdcde_idx'),
        ),
        migrations.AddIndex(
            model_name='insurance',
            index=models.Index(fields=['created_at'], name='insurance_i_created_e9c51c_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancedocument',
            index=models.Index(fields=['insurance'], name='insurance_i_insuran_897bf0_idx'),
        ),
    ]
