# Generated by Django 5.2.9 on 2026-02-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedocument',
            name='document',
            field=models.FileField(upload_to='insurance-docs/'),
        ),
    ]
