# Generated by Django 5.2.9 on 2026-02-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insurancedocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedocument',
            name='document',
            field=models.FileField(upload_to='insurance/'),
        ),
    ]
