# Generated by Django 5.2.7 on 2025-11-12 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0008_alter_medicalhistory_diagnosis_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('head_of_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_head', to='patients.patient')),
            ],
        ),
    ]
