# Generated by Django 5.2.7 on 2025-11-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(choices=[('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('spouse', 'Spouse'), ('other', 'Other')], max_length=20),
        ),
    ]
