# Generated by Django 5.2.7 on 2025-11-04 03:10

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhar_number',
            field=utils.fields.EncryptedCharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=utils.fields.EncryptedCharField(blank=True, max_length=256, null=True),
        ),
    ]
