# Generated by Django 5.2.7 on 2025-11-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhar_number',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
