# Generated by Django 5.2.7 on 2025-11-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_vitals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vitals',
            new_name='Vital',
        ),
    ]
