# Generated by Django 5.2.7 on 2025-11-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_vitals_vital'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('disease', 'Disease'), ('surgery', 'Surgery'), ('allergy', 'Allergy'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('diagnosis_code', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('chronic', 'Chronic')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='patients.patient')),
            ],
        ),
    ]
