# Generated by Django 5.2.7 on 2025-11-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_medicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='diagnosis_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('chronic', 'Chronic')], max_length=256),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='type_of',
            field=models.CharField(choices=[('disease', 'Disease'), ('surgery', 'Surgery'), ('allergy', 'Allergy'), ('Other', 'Other')], max_length=256),
        ),
    ]
