# Generated by Django 5.2.7 on 2025-11-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('hospital', models.CharField(max_length=100)),
            ],
        ),
    ]
