# Generated by Django 5.2.7 on 2025-11-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_accessrequest'),
        ('patients', '0008_alter_medicalhistory_diagnosis_code_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.UniqueConstraint(fields=('doctor', 'patient'), name='unique_doctor_patient_request'),
        ),
    ]
