# Generated by Django 5.2.7 on 2025-11-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_encounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
