# Generated by Django 5.2.9 on 2025-12-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
